# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

sudo: false
dist: trusty

branches:
  only:
    - master

env:
  global:
    secure: "SHFMzDL5m4rYCxuOEKgMm78aFsOGAYOtKM3C8LRv0ZCtmmEnnRkQ+YiwaA4tGOW9StoMX2zeFb9YdrDEYm4BY424y0Xzn5lAdL/xA2a82Q6gmU6TByD1Ue94wzmL0MVaWY/bEWM1M8u0X3zuqiC4oh6vzG8mEhPBwu2sJRyDRzK8uVz7eWqoCSCbswxh7YanGxqp59BLMPQLLdcF1Wo9OOd9KU4ZKxSiLOBbUTeNYCy0CO/k7QiveI/FDkgEoRsy6oyyTdYkrr2TDGoJSHZ2vnxjNva7yG8qEM62GsvKghc54666u+pV8yG4hSQCNRSshJOOjU2Uh3/3tllA7kNcO3jlneSM0+roaGmbnPHVgK51LkLkeQdbNpf+c4MMeS8yJIh+UsBODDkHopTnjT6P4eXJD/VY4ZUYNFb0I1js6gxGGun0fl0gLIGJCMZrGpSn7qR6+yCQG/+NMh9UHsHLDeqz84AUZKPFCR51BW3yiTjlurU/FC6uOTCzjAVowchObOyYtffKKPvuLBXOxCiewtMn/9dQkxjejEEnHX/3p+QUrsmp/QuCMB2RhxChsU0XADxyaNpG1YI5BHsyBH9CjOFutthsgL+uzxfGwICqmmMbRo8jCN8CxVr529u3cjZaeiZuucyx+XPfYDuPonC45CsO8Cr6wvRJlLI7ttUnDJY="


matrix:
  include:
    - env: PYTHON=2.7 CONDA_PY=27
    - env: PYTHON=3.4 CONDA_PY=34
    - env: PYTHON=3.5 CONDA_PY=35
    - env: PYTHON=3.6 CONDA_PY=36

before_install:

  # Install Miniconda
  - travis_retry wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

  # Setup environment
  - travis_retry conda update --yes conda
  - conda config --set always_yes yes
  - conda config --append channels ecpy
  - conda install conda-build anaconda-client -q
  - conda info -a
  - conda create -n travisci --yes python=$PYTHON pip
  - source activate travisci
  - CONDA_INSTALL="conda install -q"
  - PIP_INSTALL="pip install -q"

  # Setup conda build output directory
  - cd ~
  - mkdir conda-bld-out
  - cd conda-bld-out
  - export CONDA_BLD_PATH=$(pwd)

  # Install ecpy dependencies
  - $CONDA_INSTALL pyqt numpy ecpy

  # Intall test tools
  - $CONDA_INSTALL pytest
  - $PIP_INSTALL pytest-cov pytest-catchlog pytest-timeout
  - $PIP_INSTALL https://github.com/MatthieuDartiailh/enaml_coverage_plugin/tarball/master

  # Install codecov report tools
  - $PIP_INSTALL codecov

install:

  # Install ecpy_pulses
  - cd $TRAVIS_BUILD_DIR
  - conda build conda -q  # Package building does run only very minimal tests
  - conda install ecpy_pulses --use-local --yes -q --override-channels
  - cd ~

before_script:
  # I need a (fake) display on Travis so I need to start a X server.
  - export DISPLAY=:99.0
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  # Run the ecpy_pulses test suite
  - cd $TRAVIS_BUILD_DIR
  - py.test tests --cov ecpy_pulses --cov-report xml

after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov
  after_success:
  - cd $TRAVIS_BUILD_DIR
  - codecov
  - if [ "$TRAVIS_PULL_REQUEST" = false ]; then bash continuous-integration/deploy.sh; fi
